OFFICERS = [
    {"name": "Marquez, Jian Kalel D.", "role": "Data Analytics", "department": "Data"},
    {"name": "De Castro, Juan Carlo C.", "role": "Software Engineer Staff", "department": "Tech"},
    {"name": "Sison, Anoucshka Ysabeli A.", "role": "UI/UX Lead", "department": "Creative"},
    {"name": "Aaron Matthew A. Francisco", "role": "Mobile Development Lead", "department": "Tech"},
    {"name": "Galang, Joaquin L.", "role": "Web Development Lead", "department": "Tech"},
    {"name": "Alva, Eisha Janel T.", "role": "Cloud Development Lead", "department": "Tech"},
    {"name": "Palao, Maria Athaliah December G.", "role": "Data Scientist Lead", "department": "Data"},
    {"name": "Mariano, Adrian Kyle S.", "role": "Mobile Development Staff", "department": "Tech"},
    {"name": "Almendral, Sean Simone S.", "role": "Data Scientist Staff", "department": "Data"},
    {"name": "Gonzales, Ellaine P.", "role": "Data Scientist Staff", "department": "Data"},
    {"name": "Lenon, Danielle Laurence B.", "role": "Software Engineer Lead", "department": "Tech"},
    {"name": "Dizon, Kirsten Dwayne", "role": "AI/ML Lead", "department": "Data"},
    {"name": "Padilla, Kervin Clyde", "role": "Cloud Development Staff", "department": "Tech"},
    {"name": "Tadique, Angelica Mae A.", "role": "Data Scientist Staff", "department": "Data"},
    {"name": "Quizon, Andre Thomas M.", "role": "Cloud Development Staff", "department": "Tech"},
    {"name": "Manabat, Alexander L.", "role": "Web Development Staff", "department": "Tech"},
    {"name": "Santos, Maria Chloie S.", "role": "Lead Secretariat", "department": "Secretariat"},
    {"name": "Jimenez, Graciella Mhervie D.", "role": "Events Lead Officer", "department": "Events"},
    {"name": "Torres, Denise Andrea L.", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Doton, John Harold D.", "role": "Internal Relation Officer", "department": "Internal"},
    {"name": "Mendoza, Shane S.", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Pascua, Maria Niña Grace L.", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Alejandro, Francine Angela G.", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Decilio, Yohanna A.", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Trillanes, Alfred", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Reyes, Yzabela Denise M.", "role": "Events Staff", "department": "Events"},
    {"name": "Bathan, Pia Mikaela E.", "role": "Events Staff", "department": "Events"},
    {"name": "Berceles, John Benedict B.", "role": "Events Staff", "department": "Events"},
    {"name": "Bermudo, Jeanne Claris", "role": "Events Staff", "department": "Events"},
    {"name": "Valencia, Chean Ryan Z.", "role": "Documentation Lead", "department": "Documentation"},
    {"name": "Cabutihan, Shawn Uriel S.", "role": "Social Media Manager", "department": "Marketing"},
    {"name": "Yalung, Eya Isabel G.", "role": "Graphic Design Lead", "department": "Creative"},
    {"name": "Tadique, Angelica Mae A.", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Joves, Carla D.", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Abasolo, Julia Adriana D.", "role": "Social Media Staff", "department": "Marketing"},
    {"name": "Alva, Eisha Janel T.", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Sabando, Aldrich Gavriel A.", "role": "Social Media Staff", "department": "Marketing"},
    {"name": "Dayrit, Jelsie Hazel S.", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Sora, Athena Lexi Charlize B.", "role": "Social Media Staff", "department": "Marketing"},
    {"name": "Cabrera, Dylan Chloe B.", "role": "Social Media Staff", "department": "Marketing"},
    {"name": "Laxamana, Kiara Mariz", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Luz Angelo Ropero", "role": "Marketing Lead", "department": "Marketing"},
    {"name": "Masato Martin", "role": "Community Relation Officer", "department": "Internal"},
    {"name": "Baul, Hoseff", "role": "Community Relation Staff", "department": "Internal"},
    {"name": "Salalac, Aaron Noel", "role": "Community Relation Officer", "department": "Internal"},
    {"name": "Quilantang, Grant Mihkael D.", "role": "Community Relation staff", "department": "Internal"},
    {"name": "De Jesus Johanes S.", "role": "Marketing Staff", "department": "Marketing"},
    {"name": "Ong, Sean Keiffer S.", "role": "Auditor", "department": "Finance"},
    {"name": "Trillanes, Andrei Dominic F.", "role": "Auditor", "department": "Finance"},
    {"name": "Valderrama, Mark Harold T.", "role": "Finance Staff", "department": "Finance"},
    {"name": "Quilantang, Grant Mihkael D.", "role": "Finance Staff", "department": "Finance"},
    {"name": "Parungao, Nikko S.", "role": "Finance Staff", "department": "Finance"},
]

QUOTES = [
    "Innovation distinguishes between a leader and a follower. – Steve Jobs",
    "The best way to predict the future is to create it. – Peter Drucker",
    "Leadership is not about being in charge. It is about taking care of those in your charge. – Simon Sinek",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Great things in business are never done by one person. They’re done by a team of people. – Steve Jobs",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
    "Your most unhappy customers are your greatest source of learning. – Bill Gates",
    "Software is a great combination between artistry and engineering. – Bill Gates",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "In order to be irreplaceable, one must always be different. – Coco Chanel",
    "Technology is best when it brings people together. – Matt Mullenweg",
    "The advance of technology is based on making it fit in so that you don't even notice it. – Bill Gates",
    "Lead from the back — and let others believe they are in front. – Nelson Mandela",
    "A leader is one who knows the way, goes the way, and shows the way. – John Maxwell",
    "It’s not a bug – it’s an undocumented feature. – Anonymous",
    "The goal is not to live forever, the goal is to create something that will. – Chuck Palahniuk",
    "Leadership and learning are indispensable to each other. – John F. Kennedy",
    "Don't count the days, make the days count. – Muhammad Ali"
]
