OFFICERS = [
    {"name": "Jian Kalel D. Marquez", "role": "Data Analytics", "department": "Data"},
    {"name": "Juan Carlo C. De Castro", "role": "Software Engineer Staff", "department": "Tech"},
    {"name": "Anoucshka Ysabeli A. Sison", "role": "UI/UX Lead", "department": "Creative"},
    {"name": "Aaron Matthew A. Francisco", "role": "Mobile Development Lead", "department": "Tech"},
    {"name": "Joaquin L. Galang", "role": "Web Development Lead", "department": "Tech"},
    {"name": "Eisha Janel T. Alva", "role": "Cloud Development Lead", "department": "Tech"},
    {"name": "Maria Athaliah December G. Palao", "role": "Data Scientist Lead", "department": "Data"},
    {"name": "Adrian Kyle S. Mariano", "role": "Mobile Development Staff", "department": "Tech"},
    {"name": "Sean Simone S. Almendral", "role": "Data Scientist Staff", "department": "Data"},
    {"name": "Ellaine P. Gonzales", "role": "Data Scientist Staff", "department": "Data"},
    {"name": "Danielle Laurence B. Lenon", "role": "Software Engineer Lead", "department": "Tech"},
    {"name": "Kirsten Dwayne Dizon", "role": "AI/ML Lead", "department": "Data"},
    {"name": "Kervin Clyde Padilla", "role": "Cloud Development Staff", "department": "Tech"},
    {"name": "Angelica Mae A. Tadique", "role": "Data Scientist Staff", "department": "Data"},
    {"name": "Andre Thomas M. Quizon", "role": "Cloud Development Staff", "department": "Tech"},
    {"name": "Alexander L. Manabat", "role": "Web Development Staff", "department": "Tech"},
    {"name": "Maria Chloie S. Santos", "role": "Lead Secretariat", "department": "Secretariat"},
    {"name": "Graciella Mhervie D. Jimenez", "role": "Events Lead Officer", "department": "Events"},
    {"name": "Denise Andrea L. Torres", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "John Harold D. Doton", "role": "Internal Relation Officer", "department": "Internal"},
    {"name": "Shane S. Mendoza", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Maria Niña Grace L. Pascua", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Francine Angela G. Alejandro", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Yohanna A. Decilio", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Alfred Trillanes", "role": "Internal Relation Staff", "department": "Internal"},
    {"name": "Yzabela Denise M. Reyes", "role": "Events Staff", "department": "Events"},
    {"name": "Pia Mikaela E. Bathan", "role": "Events Staff", "department": "Events"},
    {"name": "John Benedict B. Berceles", "role": "Events Staff", "department": "Events"},
    {"name": "Jeanne Claris Bermudo", "role": "Events Staff", "department": "Events"},
    {"name": "Chean Ryan Z. Valencia", "role": "Documentation Lead", "department": "Documentation"},
    {"name": "Shawn Uriel S. Cabutihan", "role": "Social Media Manager", "department": "Marketing"},
    {"name": "Eya Isabel G. Yalung", "role": "Graphic Design Lead", "department": "Creative"},
    {"name": "Angelica Mae A. Tadique", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Carla D. Joves", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Julia Adriana D. Abasolo", "role": "Social Media Staff", "department": "Marketing"},
    {"name": "Eisha Janel T. Alva", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Aldrich Gavriel A. Sabando", "role": "Social Media Staff", "department": "Marketing"},
    {"name": "Jelsie Hazel S. Dayrit", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Athena Lexi Charlize B. Sora", "role": "Social Media Staff", "department": "Marketing"},
    {"name": "Dylan Chloe B. Cabrera", "role": "Social Media Staff", "department": "Marketing"},
    {"name": "Kiara Mariz Laxamana", "role": "Graphic Design Staff", "department": "Creative"},
    {"name": "Luz Angelo Ropero", "role": "Marketing Lead", "department": "Marketing"},
    {"name": "Masato Martin", "role": "Community Relation Officer", "department": "Internal"},
    {"name": "Hoseff Baul", "role": "Community Relation Staff", "department": "Internal"},
    {"name": "Aaron Noel Salalac", "role": "Community Relation Officer", "department": "Internal"},
    {"name": "Grant Mihkael D. Quilantang", "role": "Community Relation staff", "department": "Internal"},
    {"name": "Johanes S. De Jesus", "role": "Marketing Staff", "department": "Marketing"},
    {"name": "Sean Keiffer S. Ong", "role": "Auditor", "department": "Finance"},
    {"name": "Andrei Dominic F. Trillanes", "role": "Auditor", "department": "Finance"},
    {"name": "Mark Harold T. Valderrama", "role": "Finance Staff", "department": "Finance"},
    {"name": "Grant Mihkael D. Quilantang", "role": "Finance Staff", "department": "Finance"},
    {"name": "Nikko S. Parungao", "role": "Finance Staff", "department": "Finance"},
    {"name": "Jimwel Valdez", "role": "UI/UX Lead", "department": "Tech"},
    {"name": "Kirk Vallete", "role": "AI/ML Developer", "department": "Tech"},
    {"name": "Sofia Anne Sarmiento", "role": "UI/UX Designer", "department": "Tech"},
    {"name": "Francoise Christine O. Gurango", "role": "AI/ML Developer", "department": "Tech"},
    {"name": "Francine Louise Sanchez", "role": "Consultant", "department": "Tech"},
    {"name": "Josh Faith Gororspe", "role": "Consultant", "department": "Tech"},

]

QUOTES = [
    "Innovation distinguishes between a leader and a follower. – Steve Jobs",
    "The best way to predict the future is to create it. – Peter Drucker",
    "Leadership is not about being in charge. It is about taking care of those in your charge. – Simon Sinek",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Great things in business are never done by one person. They’re done by a team of people. – Steve Jobs",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
    "Your most unhappy customers are your greatest source of learning. – Bill Gates",
    "Software is a great combination between artistry and engineering. – Bill Gates",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "In order to be irreplaceable, one must always be different. – Coco Chanel",
    "Technology is best when it brings people together. – Matt Mullenweg",
    "The advance of technology is based on making it fit in so that you don't even notice it. – Bill Gates",
    "Lead from the back — and let others believe they are in front. – Nelson Mandela",
    "A leader is one who knows the way, goes the way, and shows the way. – John Maxwell",
    "It’s not a bug – it’s an undocumented feature. – Anonymous",
    "The goal is not to live forever, the goal is to create something that will. – Chuck Palahniuk",
    "Leadership and learning are indispensable to each other. – John F. Kennedy",
    "Don't count the days, make the days count. – Muhammad Ali"
]
